sudo: required
dist: trusty

language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - cd /tmp \
  - git clone https://github.com/phpv8/v8js.git \
  - cd v8js \
  - phpize \
  - ./configure --with-v8js=/opt/v8 LDFLAGS="-lstdc++" \
  - make \
  - make test \
  - sudo make install