language: php

php:
  - 7.1
  - 7.2

before_install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:pinepain/libv8-6.1
  - sudo apt-get install libv8-6.1 libv8-6.1-dev
  - git clone https://github.com/phpv8/v8js.git
  - cd v8js
  - phpize
  - ./configure --with-v8js=/opt/libv8-6.1
  - make

install:
  - travis_retry composer install --no-interaction --prefer-source