sudo: required
dist: trusty

language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
    - printf "\n" | sudo apt-get install libv8-dev g++
    - sudo apt-get update
    - sudo pecl install v8js-0.2.0