language: php

php:
  - 7.1
  - 7.2

before_install:
  - sudo apt-get update
  - sudo apt-get install libv8-dev g++
  - git clone https://github.com/phpv8/v8js.git
  - cd v8js
  - git checkout 1.3.6
  - git pull origin 1.3.6
  - phpize
  - ./configure --with-v8js=/opt/v8
  - make
  - make install
  - phpenmod v8js
  - phpenv config-add travis.php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source